### PR TITLE
more auth tests, closing down connections

### PR DESCRIPTION
**Pull request by patrick-ryan**
added the requested tests:

- nsq requires auth but client have none
- nsq requires none, but client have one , (**this happens when you run the nsqd command without auth info**)
- auth key is wrong

I've also added some cleanup to the TCP connections and async tasks, since some were lingering esp. after running the tests. eventually could be nice to set up a context manager for reader/writer/connection which would close on exit, similar to how file opening works.

### CODE REVIEW

**Comment by patrick-ryan** [comment]
also I noticed the exceptions weren't being raised on message parse, they'll do that now and can be caught appropriately (such as the auth tests are doing)

**Comment by patrick-ryan** [comment]
converting to draft, going to write more permission-based tests

**Comment by patrick-ryan** [comment]
okay good to go for review

**Comment by aohan237** [comment]
Thanks for that I'm a little busy recently ，I will merge this ASAP if I have time

**Pull request merged**
